# Makefile for dev subfolder

EXE=../../bin/bdev

bdev : bdev.cxx
	g++ --std=c++17 -g bdev.cxx -o $(EXE)
	
adev : adev.cxx
	g++ --std=c++17 -g adev.cxx -o $(EXE)
	
#---------------------------------------	
run :
	$(EXE)
	
